# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('cantidad_empleados', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pais', models.CharField(choices=[(1, 'Colombia'), (2, 'Argentina'), (3, 'Espa\xf1a'), (4, 'Brasil'), (5, 'Venezuela'), (6, 'Ecuador')], max_length=20)),
                ('departamento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('identificacion', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=256)),
                ('apellidos', models.CharField(max_length=256)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=256)),
                ('telefono', models.CharField(max_length=50)),
                ('estado', models.BooleanField()),
                ('ciudad_nacimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cotizacion', models.DateTimeField(auto_now_add=True)),
                ('precio', models.DecimalField(decimal_places=3, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=1, max_digits=10)),
                ('total_cotizacion', models.DecimalField(decimal_places=2, max_digits=15)),
                ('medio_de_pago', models.CharField(choices=[(1, 'Debito'), (2, 'Credito'), (3, 'Efectivo')], max_length=50)),
                ('pagado', models.BooleanField()),
                ('descuento', models.DecimalField(decimal_places=1, max_digits=2)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_presupuesto', models.DateField()),
                ('cantidad_asignada', models.DecimalField(blank=True, decimal_places=3, max_digits=10)),
                ('vigencia', models.IntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=256, unique=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=3, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('nombre_completo', models.CharField(max_length=256)),
                ('identificacion', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Vendedor'),
        ),
    ]
