# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 01:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('identificacion', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=256, verbose_name='Nombre Completo')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=20)),
                ('imagen', models.ImageField(upload_to='')),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pais', models.CharField(choices=[('Colombia', 'Colombia')], max_length=20)),
                ('departamento', models.CharField(choices=[('Cesar', 'Cesar'), ('Atlántico', 'Atlántico'), ('La Guajira', 'La Guajira'), ('Magdalena', 'Magdalena'), ('Bolivar', 'Bolivar'), ('Córdoba', 'Córdoba')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ListaElectoral',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=256, unique=True)),
                ('candidatos', models.ManyToManyField(to='dashboard.Candidato')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('nombre', models.CharField(max_length=256, unique=True)),
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('identificacion', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=256, verbose_name='Nombre Completo')),
                ('genero', models.CharField(choices=[('Masculino', 'M'), ('Femenino', 'F')], max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateTimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.DateTimeField(verbose_name='Hora de fin')),
                ('activo', models.BooleanField()),
                ('candidato_seleccionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Candidato')),
                ('lista_electoral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ListaElectoral')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='candidato',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Sucursal'),
        ),
    ]
