# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='pais',
            field=models.CharField(choices=[('Colombia', 'Colombia'), ('Argentina', 'Argentina'), ('Espa\xf1a', 'Espa\xf1a'), ('Brasil', 'Brasil'), ('Venezuela', 'Venezuela'), ('Ecuador', 'Ecuador')], max_length=20),
        ),
    ]
