# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170524_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='identificacion',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='identificacion',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
