# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20170524_0609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='estado',
            new_name='activo',
        ),
    ]
