# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20170524_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
