# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20170524_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='departamento',
            field=models.CharField(choices=[('Cesar', 'Cesar'), ('Atl\xe1ntico', 'Atl\xe1ntico'), ('La Guajira', 'La Guajira'), ('Magdalena', 'Magdalena'), ('Bolivar', 'Bolivar'), ('C\xf3rdoba', 'C\xf3rdoba')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='pais',
            field=models.CharField(choices=[('Colombia', 'Colombia')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='medio_de_pago',
            field=models.CharField(choices=[('Debito', 'Debito'), ('Credito', 'Credito'), ('Efectivo', 'Efectivo')], max_length=50),
        ),
    ]
