# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20170524_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='medio_de_pago',
            field=models.CharField(choices=[('No aplica', 'No aplica'), ('Debito', 'Debito'), ('Credito', 'Credito'), ('Efectivo', 'Efectivo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='pagado',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='cantidad_asignada',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15),
        ),
    ]
