# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20170524_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='descuento',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
