# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_cliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='productos',
            field=models.ManyToManyField(to='dashboard.Producto'),
        ),
    ]
