# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-25 06:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_cotizacion_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='edad',
        ),
    ]
